<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>Image_Enhance_App_Backend_API</RootNamespace>
		<SixLaborsLicenseKey>SPL-NON-COMMERCIAL</SixLaborsLicenseKey>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
		<PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.29.0" />
		<PackageReference Include="SixLabors.ImageSharp" Version="2.1.13" />
	</ItemGroup>

	<ItemGroup>
		<None Update="codeformer.onnx">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="realesrgan-x4.onnx">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="scrfd.onnx">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
